### ISSUE TITLE
No .editorconfig or lint config for the project

### ISSUE THREAD

**Issue by maurirlz** [afriguez/shuxbot#3]
Currently, there is no .editorconfig nor .prettierrc or .eslintrc to match a common codestyle. Making a .editorconfig over a default config should suffice, if help is needed I could provide one with general code styles that most of people match. Thanks!

**Comment by maurirlz** [comment]
Sample .editorconfig file, prettier can format based on .prettierrc or .editorconfig
```
root = true

[*]
charset = utf-8
end_of_line = lf
indent_size = 2
indent_style = space
insert_final_newline = false
max_line_length = 120
tab_width = 2

[{*.cjs,*.js, *.ts}]
indent_size = 2
tab_width = 2
```

**Comment by afriguez** [comment]
Thanks for the contribution!

**Comment by maurirlz** [comment]
I will be code contributing tomorrow since this has been fixed, today I had a lot of work to do, thanks to you for being open to contribs!
